### ISSUE TITLE
Various bugs in the Command Console

### ISSUE THREAD

**Issue by Wallboy** [sharkbound/PythonTwitchBotFramework#45] opened 2022-04-15 04:12 UTC
Platform: Linux
Python 3.10

When using command_console.py, I've ran into a few different bugs:

**1)** Sometimes when using either /chat or /sendmsg, there is an exception: "TypeError: catching classes that do not inherit from Exception is not allowed" in command_console.py line 25

**Solution:** It should be `except (json.JSONDecodeError, TypeError):`

**2)** Everytime I use either /chat or /sendmsg, within about 1 minute there is an exception in the main bot script: 

`websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received`

Subsequent /chat or /sendmsg commands then result in another exception in command_console.py: 

`websockets.exceptions.ConnectionClosedError: no close frame received or sent.`

**EDIT:** Setting ping_interval=None on both the websocket server/client seems to fix this. Probably an okay solution if you're only running/connecting to the command console on the same localhost machine.

**3)** When I try to use `/sendcmd !subbal username 5000` through the command console, it tells me I don't have enough points to subtract from. However I gave the username 50000 points to test with. When I do `!subbal username 5000` directly in the chat, it works just fine. When going through the command console though, it's not retrieving the right amount of points. Is this a caching issue? 

**EDIT:** It's actually not an issue with the Command Console. It appears to be getting the balance of the bot itself, and not the specified username. The `if get_balance_from_msg(msg).balance < amount:` check on line 134 in currency_commands.py checks against the author of the message, and not the target. The `if get_balance_from_msg(msg).balance < amount:` should probably also be moved into the else clause that follows to allow the "all" to be handled correctly.

And when using something like `!subbal all 1000000` will result in negative balance. Not sure if that's intended or if it should  have a floor of 0 and not go into the negatives.

**Comment by sharkbound** [comment] 2022-04-15 15:41
Thanks for bringing this up!
i was not aware of the negative issue, i know i tested the single target mode, but seems i overlooked added a condition for checking the math with `all` target mode.
i will do a update today to fix this.

as for the command console, intend to fix it.
the command console has not received as much attention as the bot itself, i considered switching it to do `input command -> connect -> send command -> disconnect` and repeat each time.  but not entirely sure thats the answer i want to go with.

will definitely start fixing it up though, part of the problem is that the input() is blocking any async tasks, i am pretty sure there are async variants of input() on pypi, but i may try a threading approach first and have some sort of input queue

Thanks for finding this stuff!
i will definitely investigate and seeing about fixing your findings!

**Comment by sharkbound** [comment] 2022-04-21 00:51
i have started working on a proper ping/pong system for the command system, currently working on building it in a independent project to make sure it works, then i will move to implementing it for the command console/server

**Comment by sharkbound** [comment] 2022-05-01 19:47
```
2) Everytime I use either /chat or /sendmsg, within about 1 minute there is an exception in the main bot script:

websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received```
this has been resolved by using a queue in a separate thread for reading console input, its currently in a separate branch, not on pypi yet.
working on other issues as well soon

**Comment by sharkbound** [comment] 2022-07-07 00:11
these issues should all be resolved at this point, if its not just mention me

**Closed by sharkbound** 2022-07-07 00:11 UTC
Labels: working on
